name: Run linter and tests
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install -d --system
      - name: Run Linter
        run: pylint --max-line-length=119 src
      - name: Run Tests
        env:
          BINANCE_API_KEY: ${{ secrets.BINANCE_SECRET_KEY }}
          BINANCE_API_SECRET: ${{ secrets.BINANCE_SECRET_SECRET }}
        run: pytest -s
